var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var morgan = require('morgan');

var indexRouter = require('./routes/index');
var jobRouter = require('./routes/jobRoutes');
const connectToMongo = require('./config/db');

var app = express();
connectToMongo();

app.use(morgan('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', indexRouter);

// Everything was generated by express-generator except this next line
app.use('/jobs', jobRouter);

module.exports = app;
